### PR TITLE
Feature azure pipeline

### PR DESCRIPTION
**Pull request by gusmith**
Add a azure pipeline build scripts, pointing to https://dev.azure.com/data61/Anonlink
This is currently not building because we need to create a CI user in dockerhub who could push images to `anonlink-app`, `anonlink-ngninx` and `anonlink-benchmark`. The remaining should work now (tested on a project under my name).

It should be doing the same steps are what is done in Jenkins, but some steps are not done:
 - [x] building and publishing the documentation -> use a documentation builder image to allow the frontend to build and serve the documentation.
 - [x] building the docs tutorials and testing them ->  image stored in dockerhub repo `data61/anonlink-docs-tutorials`
 - [x]  remove the jenkinsfile when we are happy with the pipeline in Azure, and change the brnach protection to use the corresponding checks.

Note: some changes may break the jenkins pipeline.

### CODE REVIEW

**Comment by hardbyte** [comment]
@gusmith I've created the docker hub account and given it write permissions to the anonlink docker repositories - details sent to you on keybase.

Building the documentation should be part of building the `nginx` container.

**Comment by gusmith** [comment]
Documentation are now built and included in the `anonlink-nginx` image.
Azure can also push the images to dockerhub (CI user has been created and added).
I've updated the description of the PR with the remaining tasks.

**Comment by gusmith** [comment]
With changes to the benchmark dockerfile, building the image went from 15 minutes to 2 minutes. The resulting image is way bigger, but it is not supposed to be used for anything else than CI.

**Comment by gusmith** [comment]
Tutorials are now also tested. Dockerhub repo is `data61/anonlink-docs-tutorials`.

**Comment by gusmith** [comment]
But one test is consistently failing with a timeout of 60 seconds:
`test_run_mapping_results[mapping_project0]` in the integration tests.

**Pull request merged**
